"""add relations

Revision ID: 10cc31cb7301
Revises: 4634302cfaae
Create Date: 2013-03-31 16:35:18.090020

"""

# revision identifiers, used by Alembic.
revision = '10cc31cb7301'
down_revision = '4634302cfaae'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'relations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('relation_name', sa.String(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=True),
        sa.Column('src_id', sa.Integer(), nullable=False),
        sa.Column('tgt_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['src_id'], ['pictures.id'],),
        sa.ForeignKeyConstraint(['tgt_id'], ['pictures.id'],),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('relation_name', 'src_id', 'tgt_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    ### end Alembic commands ###
