"""Add taggings

Revision ID: 2945fc8dea82
Revises: 118ce993aa3c
Create Date: 2013-03-29 12:56:46.818600

"""

# revision identifiers, used by Alembic.
revision = '2945fc8dea82'
down_revision = '118ce993aa3c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raw_id'], ['raw.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'classifications', u'key')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'classifications', sa.Column(u'key', sa.VARCHAR(), nullable=True))
    op.drop_table('categories')
    op.drop_table('tags')
    ### end Alembic commands ###
