"""add picture

Revision ID: 4634302cfaae
Revises: 5a06a500e9c6
Create Date: 2013-03-30 22:47:23.048367

"""

# revision identifiers, used by Alembic.
revision = '4634302cfaae'
down_revision = '5a06a500e9c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'pictures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('key', sa.String(), nullable=False),
        sa.Column('camera_model', sa.String(), nullable=True),
        sa.Column('datetime', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    ### end Alembic commands ###
